### ISSUE TITLE
Unnecessary IF

### ISSUE THREAD

**Issue by rustammm** [imustafin/TatarLiner#1]
Can [this](https://github.com/imustafin/TatarLiner/blob/master/src/ru/litsey2/robo/tatarliner/BtPinger.java#L53) happen?

[Here](https://github.com/imustafin/TatarLiner/blob/master/src/ru/litsey2/robo/tatarliner/BtPinger.java#L46) You set the value _stopped_ and it's not changing before that IF block.

**Comment by imustafin** [comment]
When [stop()](https://github.com/imustafin/TatarLiner/blob/master/src/ru/litsey2/robo/tatarliner/BtPinger.java#L70) method is called (e.g. from other thread) `stopped` is changed.
